#!/usr/bin/env python3
"""
基于比对结果生成 BaiduPCS-Go 增量下载命令并执行校验
"""

import argparse
import json
import os
import subprocess
import sys


def run_incremental_download(plan_json, pcs_bin, dry_run=False):
    with open(plan_json, "r", encoding="utf-8") as f:
        plan = json.load(f)

    remote_base = plan["remote_base"].rstrip("/")
    local_base = plan["local_base"].rstrip("/")
    missing = plan.get("missing_in_local", [])

    print(f"Total missing files to download: {len(missing)}")
    if not missing:
        print("Everything is already up-to-date locally!")
        return True

    # 按照目录层级分组，优化批量下载指令
    dirs_map = {}
    for rel in missing:
        parent_rel = os.path.dirname(rel)
        dirs_map.setdefault(parent_rel, []).append(rel)

    print(f"Grouped into {len(dirs_map)} target directories.")

    success_count = 0
    fail_list = []

    for parent_rel, files in sorted(dirs_map.items()):
        target_local_dir = os.path.join(local_base, parent_rel) if parent_rel else local_base
        os.makedirs(target_local_dir, exist_ok=True)

        remote_targets = [f"{remote_base}/{f}" for f in files]
        cmd = [pcs_bin, "download", "--saveto", target_local_dir] + remote_targets

        print(f"\n[SYNC] Downloading {len(remote_targets)} file(s) to: {target_local_dir}")
        if dry_run:
            print(" DRY RUN:", " ".join(cmd[:6]) + (" ..." if len(cmd) > 6 else ""))
            continue

        ret = subprocess.run(cmd)
        if ret.returncode != 0:
            print(f"[ERROR] BaiduPCS-Go download returned non-zero code for directory {target_local_dir}")

        # 检查本地文件是否真正落地
        for f in files:
            local_path = os.path.join(local_base, f)
            if os.path.exists(local_path):
                success_count += 1
            else:
                fail_list.append(f)

    if dry_run:
        print("\nDry run completed.")
        return True

    print(f"\n[Execution Summary]")
    print(f"  Successfully downloaded: {success_count} / {len(missing)}")
    print(f"  Failed / missing: {len(fail_list)}")

    if fail_list:
        print("[FAIL] The following files were not found locally after download:")
        for fail in fail_list[:10]:
            print(f"  - {fail}")
        return False

    return True


def main():
    parser = argparse.ArgumentParser(description="Download missing files incrementally via BaiduPCS-Go.")
    parser.add_argument("--plan-json", required=True, help="Comparison JSON generated by compare_manifest.py")
    parser.add_argument(
        "--pcs-bin",
        default=os.environ.get("PCS_BIN", os.path.expanduser("~/bin/BaiduPCS-Go")),
        help="Path to BaiduPCS-Go binary (override with --pcs-bin or PCS_BIN)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print download plan without executing")

    args = parser.parse_args()
    ok = run_incremental_download(args.plan_json, args.pcs_bin, dry_run=args.dry_run)
    if not ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
